# DataFetcher 클래스에 대한 테스트 코드

In [1]:
import lawdigest_data_pipeline as data_pipeline

# Fetcher 인스턴스 생성 
fetcher = data_pipeline.DataFetcher()

## fetch_bills_data - 법안 데이터 수집

In [5]:
bills_df = fetcher.fetch_bills_data(start_date="2025-07-07", end_date="2025-07-07", age="22")

bills_df

📌 [2025-07-07 ~ 2025-07-07] 의안 주요 내용 데이터 수집 시작...
➡️  첫 페이지 요청하여 전체 데이터 개수 확인 중...

📥 데이터 수집 중: 100%|██████████| 27/27 [00:00<?, ?개/s]

🎉 다운로드 완료! 총 27개의 데이터를 수집했습니다. 📊
✅ [INFO] 총 27 개의 법안 수집됨.
✅ [INFO] 데이터 컬럼 필터링을 수행합니다.
✅ [INFO] 결측치 처리 완료. 27 개의 법안 유지됨.

📌 발의일자별 수집한 데이터 수:
proposeDate
2025-07-07    27
Name: count, dtype: int64

,proposeDate,billId,billName,billNumber,summary,stage,proposerKind,assemblyNumber
0,2025-07-07,PRC_N2L5L0T4S1S0Q1R0Q2Q9M3M5K6L6K1,가사소송법 전부개정법률안(서영교의원 등 12인),2211325,제안이유\r\n\r\n 「가사소송법」은 제정ㆍ시행(1991. 1. 1.)된 지 3...,소관위접수,의원,22
1,2025-07-07,PRC_S2A5A0Y7Z0X4Y1W4X4F9F5D3E3C9B8,농어업재해대책법 일부개정법률안(서영교의원 등 10인),2211324,제안이유\r\n\r\n 최근 기후변화로 인해 농어업재해의 발생 빈도가 잦아지고 강...,대안반영폐기,의원,22
2,2025-07-07,PRC_N2N5L0K6L2J0J1R7S2Q4R5P8Q5O2W2,도로법 일부개정법률안(임호선의원 등 10인),2211323,제안이유 및 주요내용\r\n\r\n 교통사고는 운전자의 잘못만으로 발생하지 않고 ...,소관위심사,의원,22
3,2025-07-07,PRC_X2X5F0E7E0C1D1B1C2K8K0J7J3H5I8,전기통신사업법 일부개정법률안(민홍철의원 등 13인),2211322,제안이유 및 주요내용\r\n\r\n 현행법상 「전파법」에 따라 할당받은 주파수를 ...,소관위심사,의원,22
4,2025-07-07,PRC_B2Z5A0Z6G3H0F0G9E4F7D5D5M8K1K7,경계선지능인 평생교육 지원법안(홍기원의원 등 13인),2211321,제안이유\r\n\r\n 경계선지능인은 일반적으로 지능지수(IQ)가 71∼84에 해...,소관위심사,의원,22
...,...,...,...,...,...,...,...,...
22,2025-07-07,PRC_D2E5C0D7Y0Z1Y1Y5W4X5V3D8E7C8C4,콘텐츠산업 진흥법 일부개정법률안(김미애의원 등 15인),2211303,제안이유 및 주요내용\r\n\r\n 최근 K-콘텐츠가 세계적인 주목을 받으며 국가...,소관위심사,의원,22
23,2025-07-07,PRC_K2S5S0Q6R2P5Q1O6P4X8X5V6U5V6T4,농어촌정비법 일부개정법률안(서천호의원 등 10인),2211302,제안이유 및 주요내용\r\n\r\n 현행법은 빈집의 매입과 활용에 관한 규정을 두...,소관위심사,의원,22
24,2025-07-07,PRC_R2R5P0Q6Y1Z1X0W9W5U9V2D6D1C8A3,미래조선업의 경쟁력 강화 및 지원에 관한 특별법안(허성무의원 등 10인),2211301,제안이유\r\n\r\n 국제사회가 해양부문의 온실가스 감축을 본격적으로 추진함에 ...,소관위접수,의원,22
25,2025-07-07,PRC_H2F5G0O6M2N4L0L9K5L9G4H1F8G7E7,수산업·어촌 발전 기본법 일부개정법률안(윤준병의원 등 15인),2211300,제안이유 및 주요내용\r\n\r\n 현재 「배타적 경제수역에서의 외국인어업 등에 ...,소관위심사,의원,22
26,2025-07-07,PRC_P2X5Y0W6W2U4T0U9C5C9A0B2A6A6Y2,배타적 경제수역에서의 외국인어업 등에 대한 주권적 권리의 행사에 관한 법률 일부개정...,2211299,제안이유 및 주요내용\r\n\r\n 현행법에 따라 우리나라의 배타적 경제수역에서 ...,소관위심사,의원,22

In [ ]:

# 3. 해당 법안들의 공동발의자 수집
# (bills_df를 전달하지 않아도, 
#  캐시된 self.df_bills를 찾아 자동으로 사용)
coactors_df = fetcher.fetch_bills_coactors()

# 4. 다른 기간의 법안 수집 (인스턴스 재사용)
feb_bills_df = fetcher.fetch_bills_data(start_date="2024-02-01", 
                                        end_date="2024-02-29", 
                                        age="21")

In [6]:
fetcher.fetch_bills_timeline(start_date='2025-11-21', end_date='2025-11-21', age='22')

📌 [INFO] [2025-11-21 ~ 2025-11-21] 의정활동 데이터 수집 시작...
✅ [INFO] 2025-11-21 | 📄 Page 1 | 📊 100 개 추가됨. 총 100 개 수집됨.
✅ [INFO] 2025-11-21 | 📄 Page 2 | 📊 100 개 추가됨. 총 200 개 수집됨.
✅ [INFO] 2025-11-21 | 📄 Page 3 | 📊 100 개 추가됨. 총 300 개 수집됨.
✅ [INFO] 2025-11-21 | 📄 Page 4 | 📊 94 개 추가됨. 총 394 개 수집됨.

✅ [INFO] 모든 파일 다운로드 완료! ⏳ 전체 소요 시간: 1.20초
📌 [INFO] 총 394 개의 의정활동 데이터 수집됨.

,SEQ,DT,BILL_KIND,AGE,BILL_NO,BILL_NM,STAGE,DTL_STAGE,COMMITTEE,ACT_STATUS,BILL_ID,LINK_URL,COMMITTEE_ID
0,1000333183107,2025-11-21,법률안,22,2200199,산업안전보건법 일부개정법률안(임이자의원 등 10인),위원회 심사,회의,기후에너지환경노동위원회,회의,PRC_O2N4M0I6H0F3E1F7N1L0K2J2M2U1T1,https://likms.assembly.go.kr/bill/billDetail.d...,9700585
1,1000333183119,2025-11-21,법률안,22,2200271,중소기업 기술혁신 촉진법 일부개정법률안(최수진의원 등 18인),위원회 심사,처리,산업통상자원중소벤처기업위원회,처리,PRC_P2N4O0J6L0J4J1H1G5H1O1P1N7O5M3,https://likms.assembly.go.kr/bill/billDetail.d...,9700481
2,1000333183120,2025-11-21,법률안,22,2200271,중소기업 기술혁신 촉진법 일부개정법률안(최수진의원 등 18인),위원회 심사,회의,산업통상자원중소벤처기업위원회,회의,PRC_P2N4O0J6L0J4J1H1G5H1O1P1N7O5M3,https://likms.assembly.go.kr/bill/billDetail.d...,9700481
3,1000333182919,2025-11-21,법률안,22,2200866,산업안전보건법 일부개정법률안(김영진의원 등 10인),위원회 심사,회의,기후에너지환경노동위원회,회의,PRC_B2A4W0V6W1U9B1A7I1J0I5G2F1N9L8,https://likms.assembly.go.kr/bill/billDetail.d...,9700585
4,1000333183151,2025-11-21,법률안,22,2200887,산업재해보상보험법 일부개정법률안(김주영의원 등 17인),위원회 심사,회의,기후에너지환경노동위원회,회의,PRC_S2A4Z0X6W2E1F1E5D2B7X2W0V5V5U5,https://likms.assembly.go.kr/bill/billDetail.d...,9700585
...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,1000333183088,2025-11-21,법률안,22,DD20549,중소기업기본법 일부개정법률안(대안)(산업통상자원중소벤처기업위원장),위원회 심사,상정,산업통상자원중소벤처기업위원회,상정,PRC_N2K5Z1M1T2X0V1B5F4P4E0K6G8M4W2,https://likms.assembly.go.kr/bill/billDetail.d...,9700481
390,1000333183089,2025-11-21,법률안,22,DD20549,중소기업기본법 일부개정법률안(대안)(산업통상자원중소벤처기업위원장),위원회 심사,처리,산업통상자원중소벤처기업위원회,처리,PRC_N2K5Z1M1T2X0V1B5F4P4E0K6G8M4W2,https://likms.assembly.go.kr/bill/billDetail.d...,9700481
391,1000333183090,2025-11-21,법률안,22,DD20549,중소기업기본법 일부개정법률안(대안)(산업통상자원중소벤처기업위원장),위원회 심사,회의,산업통상자원중소벤처기업위원회,회의,PRC_N2K5Z1M1T2X0V1B5F4P4E0K6G8M4W2,https://likms.assembly.go.kr/bill/billDetail.d...,9700481
392,1000333183091,2025-11-21,법률안,22,DD20549,중소기업기본법 일부개정법률안(대안)(산업통상자원중소벤처기업위원장),접수,제안,-,제안,PRC_N2K5Z1M1T2X0V1B5F4P4E0K6G8M4W2,https://likms.assembly.go.kr/bill/billDetail.d...,None
393,1000333183092,2025-11-21,법률안,22,DD20549,중소기업기본법 일부개정법률안(대안)(산업통상자원중소벤처기업위원장),체계자구 심사,회부,법제사법위원회,회부,PRC_N2K5Z1M1T2X0V1B5F4P4E0K6G8M4W2,https://likms.assembly.go.kr/bill/billDetail.d...,9700006